### GET PUBLIC PROFILE
GET http://localhost:3000/ HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJkYXRlIjoiMjAyNC0wOC0yOVQwMzozNTozOC40MjVaIiwiaXNzIjoibWVyY3VyaXVzLmNvbSIsInN1YiI6InB1YmxpY19hY2Nlc3MiLCJhdWQiOiJndWVzdCIsImlhdCI6MTcyNDkwMjUzOH0.8cxOnEkLEjryot4DVdgP4KDFzqV5l8doys68IdknOFiCgQz0SrIiy4KwYuL2PaKf7WZMM6yoEE-7PIoxPE_v_w