### RANDOM SECRET KEY
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "randomSecret": true,
    "message": "Just a test!"
}

### CREATE PUBLIC ACCESS 
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "createPublicAccess": true,
    "issuer": "mercurius.com"
}

### RECOVERY PUBLIC ACCESS 
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "recoveryPublicAccess": true,
    "issuer": "mercurius.com"
}

### REVOKE PUBLIC ACCESS 
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "revokePublicAccess": true,
    "issuer": "mercurius.com",
    "days": 90
}

### REMOVE EXPIRED TOKENS 
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "removeExpiredTokens": true
}
