### TOKENATOR: GENERATE SECRET KEY 
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "target": "random_secret",
    "message": "Hello! Just a random message to random secret"
}

### TOKENATOR: GENERATE PUBLIC ACCESS 
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "target": "public_access",
    "issuer": "mercurius.com"
}

### TOKENATOR: RECOVERY PUBLIC ACCESS 
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "target": "get_public_access",
    "issuer": "mercurius.com"
}

### TOKENATOR: REVOKE PUBLIC ACCESS 
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "target": "revoke_public_access",
    "issuer": "mercurius.com",
    "days": 90
}

### TOKENATOR: SHRINK REVOKED TOKENS 
POST http://localhost:3000/tokenator HTTP/1.1
accept-language: pt-BR,pt
content-type: application/json

{
    "target": "revoke_shrink"
}

### INDEX
GET http://localhost:3000 HTTP/1.1
accept-language: pt-BR,pt
